/* Generated By:JavaCC: Do not edit this line. OrientSqlTreeConstants.java Version 5.0 */
package com.orientechnologies.orient.core.sql.parser;

public interface OrientSqlTreeConstants
{
  public int JJTRID = 0;
  public int JJTPARSE = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTINTEGER = 3;
  public int JJTFLOATINGPOINT = 4;
  public int JJTNUMBER = 5;
  public int JJTSTATEMENT = 6;
  public int JJTQUERYSTATEMENT = 7;
  public int JJTSELECTWITHOUTTARGETSTATEMENT = 8;
  public int JJTSELECTSTATEMENT = 9;
  public int JJTTRAVERSESTATEMENT = 10;
  public int JJTDELETESTATEMENT = 11;
  public int JJTDELETEVERTEXSTATEMENT = 12;
  public int JJTDELETEEDGESTATEMENT = 13;
  public int JJTDELETEEDGEBYRIDSTATEMENT = 14;
  public int JJTDELETEEDGEFROMTOSTATEMENT = 15;
  public int JJTDELETEEDGETOSTATEMENT = 16;
  public int JJTDELETEEDGEVTOSTATEMENT = 17;
  public int JJTDELETEEDGEWHERESTATEMENT = 18;
  public int JJTUPDATESTATEMENT = 19;
  public int JJTUPDATEOPERATIONS = 20;
  public int JJTUPDATEITEM = 21;
  public int JJTUPDATEINCREMENTITEM = 22;
  public int JJTUPDATEREMOVEITEM = 23;
  public int JJTUPDATEPUTITEM = 24;
  public int JJTUPDATEADDITEM = 25;
  public int JJTINSERTSTATEMENT = 26;
  public int JJTINSERTBODY = 27;
  public int JJTCREATEVERTEXSTATEMENTEMPTYNOTARGET = 28;
  public int JJTCREATEVERTEXSTATEMENTEMPTY = 29;
  public int JJTCREATEVERTEXSTATEMENT = 30;
  public int JJTCREATEVERTEXSTATEMENTNOTARGET = 31;
  public int JJTCREATEEDGESTATEMENT = 32;
  public int JJTINPUTPARAMETER = 33;
  public int JJTPOSITIONALPARAMETER = 34;
  public int JJTNAMEDPARAMETER = 35;
  public int JJTPROJECTION = 36;
  public int JJTPROJECTIONITEM = 37;
  public int JJTARRAYSELECTOR = 38;
  public int JJTARRAYNUMBERSELECTOR = 39;
  public int JJTARRAYSINGLEVALUESSELECTOR = 40;
  public int JJTARRAYRANGESELECTOR = 41;
  public int JJTALIAS = 42;
  public int JJTRECORDATTRIBUTE = 43;
  public int JJTFUNCTIONCALL = 44;
  public int JJTMETHODCALL = 45;
  public int JJTLEVELZEROIDENTIFIER = 46;
  public int JJTSUFFIXIDENTIFIER = 47;
  public int JJTBASEIDENTIFIER = 48;
  public int JJTMODIFIER = 49;
  public int JJTEXPRESSION = 50;
  public int JJTMATHEXPRESSION = 51;
  public int JJTMULTEXPRESSION = 52;
  public int JJTFIRSTLEVELEXPRESSION = 53;
  public int JJTPARENTHESISEXPRESSION = 54;
  public int JJTBASEEXPRESSION = 55;
  public int JJTFROMCLAUSE = 56;
  public int JJTLETCLAUSE = 57;
  public int JJTLETITEM = 58;
  public int JJTFROMITEM = 59;
  public int JJTCLUSTER = 60;
  public int JJTCLUSTERLIST = 61;
  public int JJTMETADATAIDENTIFIER = 62;
  public int JJTINDEXIDENTIFIER = 63;
  public int JJTWHERECLAUSE = 64;
  public int JJTWHILECLAUSE = 65;
  public int JJTUNTILCLAUSE = 66;
  public int JJTORBLOCK = 67;
  public int JJTANDBLOCK = 68;
  public int JJTNOTBLOCK = 69;
  public int JJTPARENTHESISBLOCK = 70;
  public int JJTCONDITIONBLOCK = 71;
  public int JJTCOMPAREOPERATOR = 72;
  public int JJTLTOPERATOR = 73;
  public int JJTGTOPERATOR = 74;
  public int JJTNEOPERATOR = 75;
  public int JJTNEQOPERATOR = 76;
  public int JJTGEOPERATOR = 77;
  public int JJTLEOPERATOR = 78;
  public int JJTLIKEOPERATOR = 79;
  public int JJTLUCENEOPERATOR = 80;
  public int JJTNEAROPERATOR = 81;
  public int JJTWITHINOPERATOR = 82;
  public int JJTCONTAINSKEYOPERATOR = 83;
  public int JJTCONTAINSVALUEOPERATOR = 84;
  public int JJTEQUALSCOMPAREOPERATOR = 85;
  public int JJTBINARYCONDITION = 86;
  public int JJTCONTAINSVALUECONDITION = 87;
  public int JJTINSTANCEOFCONDITION = 88;
  public int JJTINDEXMATCHCONDITION = 89;
  public int JJTBETWEENCONDITION = 90;
  public int JJTISNULLCONDITION = 91;
  public int JJTISNOTNULLCONDITION = 92;
  public int JJTISDEFINEDCONDITION = 93;
  public int JJTISNOTDEFINEDCONDITION = 94;
  public int JJTCONTAINSCONDITION = 95;
  public int JJTINOPERATOR = 96;
  public int JJTINCONDITION = 97;
  public int JJTNOTINCONDITION = 98;
  public int JJTCONTAINSALLCONDITION = 99;
  public int JJTCONTAINSTEXTCONDITION = 100;
  public int JJTMATCHESCONDITION = 101;
  public int JJTORDERBY = 102;
  public int JJTGROUPBY = 103;
  public int JJTUNWIND = 104;
  public int JJTLIMIT = 105;
  public int JJTSKIP = 106;
  public int JJTTIMEOUT = 107;
  public int JJTWAIT = 108;
  public int JJTRETRY = 109;
  public int JJTCOLLECTION = 110;
  public int JJTFETCHPLAN = 111;
  public int JJTFETCHPLANITEM = 112;
  public int JJTTRAVERSEPROJECTIONITEM = 113;
  public int JJTARRAY = 114;
  public int JJTJSON = 115;


  public String[] jjtNodeName = {
    "Rid",
    "parse",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Number",
    "Statement",
    "QueryStatement",
    "SelectWithoutTargetStatement",
    "SelectStatement",
    "TraverseStatement",
    "DeleteStatement",
    "DeleteVertexStatement",
    "DeleteEdgeStatement",
    "DeleteEdgeByRidStatement",
    "DeleteEdgeFromToStatement",
    "DeleteEdgeToStatement",
    "DeleteEdgeVToStatement",
    "DeleteEdgeWhereStatement",
    "UpdateStatement",
    "UpdateOperations",
    "UpdateItem",
    "UpdateIncrementItem",
    "UpdateRemoveItem",
    "UpdatePutItem",
    "UpdateAddItem",
    "InsertStatement",
    "InsertBody",
    "CreateVertexStatementEmptyNoTarget",
    "CreateVertexStatementEmpty",
    "CreateVertexStatement",
    "CreateVertexStatementNoTarget",
    "CreateEdgeStatement",
    "InputParameter",
    "PositionalParameter",
    "NamedParameter",
    "Projection",
    "ProjectionItem",
    "ArraySelector",
    "ArrayNumberSelector",
    "ArraySingleValuesSelector",
    "ArrayRangeSelector",
    "Alias",
    "RecordAttribute",
    "FunctionCall",
    "MethodCall",
    "LevelZeroIdentifier",
    "SuffixIdentifier",
    "BaseIdentifier",
    "Modifier",
    "Expression",
    "MathExpression",
    "MultExpression",
    "FirstLevelExpression",
    "ParenthesisExpression",
    "BaseExpression",
    "FromClause",
    "LetClause",
    "LetItem",
    "FromItem",
    "Cluster",
    "ClusterList",
    "MetadataIdentifier",
    "IndexIdentifier",
    "WhereClause",
    "WhileClause",
    "UntilClause",
    "OrBlock",
    "AndBlock",
    "NotBlock",
    "ParenthesisBlock",
    "ConditionBlock",
    "CompareOperator",
    "LtOperator",
    "GtOperator",
    "NeOperator",
    "NeqOperator",
    "GeOperator",
    "LeOperator",
    "LikeOperator",
    "LuceneOperator",
    "NearOperator",
    "WithinOperator",
    "ContainsKeyOperator",
    "ContainsValueOperator",
    "EqualsCompareOperator",
    "BinaryCondition",
    "ContainsValueCondition",
    "InstanceofCondition",
    "IndexMatchCondition",
    "BetweenCondition",
    "IsNullCondition",
    "IsNotNullCondition",
    "IsDefinedCondition",
    "IsNotDefinedCondition",
    "ContainsCondition",
    "InOperator",
    "InCondition",
    "NotInCondition",
    "ContainsAllCondition",
    "ContainsTextCondition",
    "MatchesCondition",
    "OrderBy",
    "GroupBy",
    "Unwind",
    "Limit",
    "Skip",
    "Timeout",
    "Wait",
    "Retry",
    "Collection",
    "FetchPlan",
    "FetchPlanItem",
    "TraverseProjectionItem",
    "Array",
    "Json",
  };
}
/* JavaCC - OriginalChecksum=a585d2fbbf7030ed3be3682015b594f2 (do not edit this line) */
