/* Generated By:JJTree: Do not edit this line. OWhileClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import java.util.Map;

import com.orientechnologies.orient.core.db.record.OIdentifiable;

public
class OWhileClause extends OWhereClause {
  OBooleanExpression baseExpression;

  public OWhileClause(int id) {
    super(id);
  }

  public OWhileClause(OrientSql p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OrientSqlVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public boolean matchesFilters(OIdentifiable currentRecord) {
    if (baseExpression == null) {
      return true;
    }
    return baseExpression.evaluate(currentRecord);
  }

  @Override
  public String toString() {
    if (baseExpression == null) {
      return "";
    }
    return baseExpression.toString();
  }

  public void replaceParameters(Map<Object, Object> params) {
    if(baseExpression!=null) {
      baseExpression.replaceParameters(params);
    }

  }
}
/* JavaCC - OriginalChecksum=dff34994b504ceda0d85d8b2e260b50e (do not edit this line) */
